$images = Get-ChildItem -Path .\d24images -File | Sort-Object Name | Where-Object { $_.Extension -match '^(?i)(?:\.(jpg|jpeg|png|gif|webp|bmp|svg))$' }
$lines = @()
$lines += '<!DOCTYPE html>'
$lines += '<html lang="en">'
$lines += '<head>'
$lines += '  <meta charset="UTF-8">'
$lines += '  <meta name="viewport" content="width=device-width, initial-scale=1.0">'
$lines += '  <title>District 24 Image Gallery</title>'
$lines += '  <style>'
$lines += '    body { margin: 0; font-family: Arial, sans-serif; background: #111; color: #eee; }'
$lines += '    header { padding: 24px 16px; text-align: center; background: #151515; border-bottom: 1px solid #333; }'
$lines += '    header h1 { margin: 0; font-size: 2rem; }'
$lines += '    header p { margin: 8px 0 0; color: #aaa; }'
$lines += '    .gallery { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: 12px; padding: 16px; }'
$lines += '    .card { border-radius: 12px; overflow: hidden; background: #1a1a1a; box-shadow: 0 10px 30px rgba(0,0,0,.45); }'
$lines += '    .card img { width: 100%; display: block; height: 200px; object-fit: cover; }'
$lines += '    .caption { padding: 12px; font-size: 0.85rem; color: #ddd; word-break: break-word; }'
$lines += '    .caption span { display: block; color: #bbb; margin-top: 4px; font-size: 0.8rem; }'
$lines += '    .footer { text-align: center; padding: 14px 16px; color: #888; font-size: 0.9rem; }'
$lines += '    @media (max-width: 580px) { .gallery { padding: 10px; gap: 10px; } .card img { height: 160px; } }'
$lines += '    a { color: inherit; text-decoration: none; }'
$lines += '  </style>'
$lines += '</head>'
$lines += '<body>'
$lines += '  <header>'
$lines += '    <h1>District 24 Image Gallery</h1>'
$lines += '    <p>Automatically generated gallery from the <code>d24images</code> folder.</p>'
$lines += '  </header>'
$lines += '  <main class="gallery">'
foreach ($img in $images) {
    $name = $img.Name -replace '&','&amp;' -replace '<','&lt;' -replace '>','&gt;' -replace '"','&quot;'
    $path = 'd24images/' + $img.Name
    $lines += '    <article class="card">'
    $lines += '      <a href="' + $path + '" target="_blank">'
    $lines += '        <img src="' + $path + '" alt="' + $name + '">'
    $lines += '      </a>'
    $lines += '      <div class="caption">' + $name + '<span>' + $img.Length + ' bytes</span></div>'
    $lines += '    </article>'
}
$lines += '  </main>'
$lines += '  <footer class="footer">Total images: ' + $images.Count + '</footer>'
$lines += '</body>'
$lines += '</html>'
$lines | Out-File -FilePath .\gallery.html -Encoding utf8
Write-Host ('Created gallery.html with ' + $images.Count + ' images.')
